// src/constants/faqData.js
export const faqData = [
    { question: "What is ECHO?", answer: "ECHO is your personal AI companion that sees, listens, understands, and responds to you. It can recognize faces, detect emotions from text, voice, or video, and even speak back to you — making interactions more human-like and personalized." },
    { question: "What can I use ECHO for?", answer: "ECHO is designed for personal use, family safety, wellness, and smart living. You can use it to recognize family members, detect mood changes, remind you of activities, enhance smart home automation, and make security more intelligent." },
    { question: "How does face recognition work in ECHO?", answer: "You simply upload a labeled photo (e.g., \"Dad\", \"Colleague\", \"Friend\") once. ECHO saves that profile securely, and from then on, it can recognize them instantly in photos, videos, or live camera feeds." },
    { question: "How accurate is ECHO’s emotion detection?", answer: "ECHO uses advanced AI models trained on thousands of real-world emotion samples. It can detect emotions such as happiness, calm, frustration, anxiety, and exhaustion with high accuracy — and adapts to your voice and communication style over time for even better personalization." },
    { question: "Can ECHO talk back to me?", answer: "Yes! ECHO has text-to-speech capabilities. If it recognizes you or detects an emotion, it can respond naturally — for example: “Hey Sam, you sound tired. Maybe take a break.”" },
    { question: "Does ECHO work in real-time?", answer: "Absolutely. Whether it’s from your phone, laptop, or smart home device, ECHO processes and responds instantly using its optimized backend." },
    { question: "Is my data safe with ECHO?", answer: "Yes. Privacy and security are core to ECHO’s design. Your face and voice data are stored locally or securely encrypted, no personal data is sold to third parties, and you control what’s stored and can delete your data anytime." },
    { question: "Can ECHO be customized?", answer: "Yes! You can add your own face database, change response styles (formal, casual, playful), configure alerts and reminders, and integrate with smart home systems." },
    { question: "Do I need the internet for ECHO to work?", answer: "Basic functions like face recognition and emotion detection can run offline. Features like real-time voice chat and cloud backup require an internet connection." },
    { question: "Where can I get ECHO?", answer: "ECHO will be available as a standalone desktop & mobile app, a smart home integration package, and an Enterprise API for custom integrations." }
];
